# experiment name
exp_name : "ood_experiment/"

# training
train : False
posthoc : False
kl_weight: 1e-6
train_samples: 1

# test
ood : True
missing_data_imputation : False
test_samples: 100

# data
dataset : "fashionmnist"
ood_dataset : "mnist"
batch_size: 50

# model
pretrained : False
no_conv : False
latent_size : 2

# hessian
backend : "layer" 
approximation : "mix" #block, exact, diag, mix
hessian_memory_factor : 0 
one_hessian_per_sampling : False