# experiment name
exp_name : "ood_experiment/"

# training
train : True
kl_weight: 0.00001
learning_rate : 1e-4

# test
ood : True
missing_data_imputation : False

# data
dataset : "fashionmnist"
ood_dataset : "mnist"
batch_size: 50

# model
pretrained : False
no_conv : False
latent_size : 2
use_var_decoder : True