# experiment name
exp_name : "ood_experiment/"

# training
train : True

# test
ood : True

# data
dataset : "mnist"
ood_dataset : "kmnist"
batch_size: 50

# model
pretrained : False
no_conv : True
latent_size : 2
use_var_decoder : False